### ISSUE TITLE
This package can't resolve dependence on Sailfish SDK

### ISSUE THREAD

**Issue by TuQinggang** [mer-hybris/geoclue-providers-hybris#38]
Hello:
     I want rebuild this package localy. And I use the Latest sailfih SDK(3.5.7),but it can't get dependence package,How can I resolve it ?
     
![image](https://user-images.githubusercontent.com/24808608/129036733-ed32eb17-f068-4734-bef4-88260509c35c.png)

**Comment by mlehtima** [comment]
For which device are you building that? Seeing that you are building for aarch64 based device which normally do not use the hal plugin but use the binder plugin in the same repo which has a separate spec file. You need to specify during build which spec to use.

**Comment by TuQinggang** [comment]
> For which device are you building that? 
 I build it for a tablet,the CPU is RK3399(archtecture is arm64 and Android BSP=7.1)
>Seeing that you are building for aarch64 based device which normally do not use the hal plugin but use the binder plugin in the same repo which has a separate spec file. You need to specify during build which spec to use.
 I use the spec file "geoclue-providers-hybris-binder.spec" but the depends error still.I find the package "**qofonoext**" on SUSE and CentOS and sailfish github repos,but still can't find this package.can you tell me where can I get the depends? Thanks :)

**Comment by mlehtima** [comment]
Hi, Android 7 based device require the hal plugin because the binder plugin is only supported on android 8 and newer. How did you build the rest of the device adaptation?

**Comment by TuQinggang** [comment]
> Hi, Android 7 based device require the hal plugin because the binder plugin is only supported on android 8 and newer. How did you build the rest of the device adaptation?

my tablet is run on a linux OS(the kernal is from Android),but the system can't run well because some driver is designed for Android only . I have the full Andriod SDK from vendor.So I want the linux programs use Android driver by libhybris.

I have build the libhybris done,and passed the GPS test.So I want to build this package for a GPS demo.but it can't resolve the depends.
So can you teach me how can I rebuild this package on my machine? :) Thank you !

**Comment by TuQinggang** [comment]
Hello,can you tell me where can I get the depends or how canI build it ,Thanks! 
:pray:

**Comment by TuQinggang** [comment]
I had solved this problem,I should build the hal-droid-device first,close this issue.
